### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by GoesToEleven** [GoesToEleven/GolangTraining#1]
- [ ] testing - https://golang.org/doc/code.html#Testing
- [ ] init function - http://stackoverflow.com/questions/24790175/when-is-the-init-function-in-go-golang-run
- [ ] string runes - https://blog.golang.org/strings
- [ ] read - https://golang.org/doc/effective_go.html

**Comment by jeremejazz** [comment]
Would be great. This is very important in every programming language
